### ISSUE TITLE
Move 'results' to a different path

### ISSUE THREAD

**Issue by edsiper** [calyptia/benchmark-framework#6]
Currently the **results** are inside the `scenarios/` directory. 

Ideally we want to have them split in two directories, e.g:

- scenarios/tail_null/
- results/tail_null

so when its time to cleanup the results can be done in a single directory and not inside every scenario

**Comment by Syn3rman** [comment]
Hey @edsiper,
is this directory structure close to what we want? (I've run it only for one agent and one scenario to get an idea of how to structure it)
![image](https://user-images.githubusercontent.com/31011197/163189905-0836fb50-8b9d-4d6f-a9e3-e0a24500c9cc.png)
